/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SddRouteImport } from './routes/sdd'
import { Route as AiToUiRouteImport } from './routes/ai-to-ui'
import { Route as IndexRouteImport } from './routes/index'

const SddRoute = SddRouteImport.update({
  id: '/sdd',
  path: '/sdd',
  getParentRoute: () => rootRouteImport,
} as any)
const AiToUiRoute = AiToUiRouteImport.update({
  id: '/ai-to-ui',
  path: '/ai-to-ui',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-to-ui': typeof AiToUiRoute
  '/sdd': typeof SddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-to-ui': typeof AiToUiRoute
  '/sdd': typeof SddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-to-ui': typeof AiToUiRoute
  '/sdd': typeof SddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-to-ui' | '/sdd'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-to-ui' | '/sdd'
  id: '__root__' | '/' | '/ai-to-ui' | '/sdd'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiToUiRoute: typeof AiToUiRoute
  SddRoute: typeof SddRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sdd': {
      id: '/sdd'
      path: '/sdd'
      fullPath: '/sdd'
      preLoaderRoute: typeof SddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-to-ui': {
      id: '/ai-to-ui'
      path: '/ai-to-ui'
      fullPath: '/ai-to-ui'
      preLoaderRoute: typeof AiToUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiToUiRoute: AiToUiRoute,
  SddRoute: SddRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
